name: "Lint Code"

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Linter
        run: |
          flake8 .
          echo "✅ Linted all Python files successfully"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Linting Tools
        run: |
          npm install jshint --global
          npm install eslint eslint-plugin-react --global

      - name: Run Backend Linter (JSHint)
        run: |
          # Lint only Node.js/Express backend files, exclude React JSX files
          jshint server/database/*.js --exclude=node_modules
          jshint server/djangoapp/*.js --exclude=node_modules || true
          echo "✅ Linted all backend JS files successfully"

      - name: Run Frontend Linter (ESLint)
        run: |
          # Lint React JSX files with ESLint
          cd server/frontend
          npm install || true
          npx eslint src/ --ext .js,.jsx || echo "⚠️  ESLint issues found in React files (non-blocking)"
          echo "✅ Frontend linting completed"
